server:
  port: 8080
  tomcat:
    threads:
      # 저사양 인스턴스에서 스레드 경합을 유도하기 위해 50~100 정도로 설정
      max: 100
    accept-count: 50
    max-connections: 1000

logging:
  level:
    root: info
    # 테스트 중 로그가 너무 많으면 디스크 I/O가 병목이 되므로 최소화